# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)

## NeoForge
neo_version=21.1.83
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Mod Info
mod_id=crabbersdelight
mod_name=Crabber's Delight
mod_license=MIT License
mod_version=1.2.0
mod_group_id=alabaster.crabbersdelight
mod_authors=AlabasterLeking
mod_description=A maritime addon for Farmer's Delight!

## Dependency Info

# Farmer's Delight
farmersdelight_version=6154807

# JEI
jei_minecraft=1.21
jei_version=19.8.2.99

# AppleSkin
appleskin_version=mc1.21-3.0.5

# CraftTweaker
crafttweaker_minecraft=1.21
crafttweaker_version=20.0.21
crafttweaker_ap_version=3.0.0.15