modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]

modId="crabbersdelight"

version="1.0.1"
displayName="Crabber's Delight"
logoFile="crabbersdelightbanner.png"
credits="Thank you to vectorwing for creating Farmer's Delight! Special thanks to the following translators:
Simplified Chinese: Junnaturefox"
authors="Alabaster Leking"
description='''A maritime addon for Farmer's Delight'''

[[dependencies.crabbersdelight]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.crabbersdelight]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.crabbersdelight]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.1,)"
ordering = "NONE"
side = "BOTH"
