modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]

modId="sniffersdelight"

version="1.0.0"
displayName="Sniffer's Delight"
logoFile="sniffersdelight-final.png"
credits="Thank you to vectorwing for creating Farmer's Delight!"
authors="Alabaster Leking"
description='''A maritime addon for Farmer's Delight'''

[[dependencies.sniffersdelight]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.sniffersdelight]]
modId="minecraft"
mandatory=true
versionRange="[1.20, 1.20.1)"
ordering="NONE"
side="BOTH"

[[dependencies.sniffersdelight]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.2,)"
ordering = "NONE"
side = "BOTH"