modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"

[[mods]]

modId="crabbersdelight"

version="1.1.1"
displayName="Crabber's Delight"
logoFile="crabbersdelightbanner.png"
credits="Thank you to vectorwing for creating Farmer's Delight!"
authors="Alabaster Leking"
description='''A maritime addon for Farmer's Delight'''

[[dependencies.crabbersdelight]]
modId="forge"
mandatory=true
versionRange="[40.1.46,)"
ordering="NONE"
side="BOTH"

[[dependencies.crabbersdelight]]
modId="minecraft"
mandatory=true
versionRange="[1.18.]"
ordering="NONE"
side="BOTH"

[[dependencies.crabbersdelight]]
modId = "farmersdelight"
mandatory = true
versionRange = "[1.2.1,)"
ordering = "NONE"
side = "BOTH"
