modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT License"

[[mods]]

modId="crabbersdelight"

version="1.1.7"
displayName="Crabber's Delight"
logoFile="crabbersdelightbanner.png"
credits="Thank you to vectorwing for creating Farmer's Delight!"
authors="Alabaster Leking"
description='''A maritime addon for Farmer's Delight'''
itemIcon = "crabbersdelight:clawster"

[[dependencies.crabbersdelight]]
modId="neoforge"
type="required"
versionRange="[21.0.102-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.crabbersdelight]]
modId="minecraft"
type="required"
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.crabbersdelight]]
modId = "farmersdelight"
type="required"
versionRange = "[1.2.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crabbersdelight]]
modId = "geckolib"
type="required"
versionRange = "[4.2.3,)"
ordering = "NONE"
side = "BOTH"
